tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/cert.crt
        keyFile: /certs/cert.key

http:
  routers:
    notify-ws:
      rule: 'Host(`{{ env "DOMAIN" }}`) && PathPrefix(`/socket.io`)'
      entryPoints: [websecure]
      tls: {}
      service: notification

    ui:
      rule: 'Host(`{{ env "DOMAIN" }}`)'
      entryPoints: [websecure]
      tls: {}
      service: ui

  services:
    notification:
      loadBalancer:
        servers:
          - url: "http://notification-service:3004"

    ui:
      loadBalancer:
        servers:
          - url: "http://ui-layer:3000"
